In [9]:
import numpy as np

In [246]:
# W is K x D
# K - num classes
# D - dimensions of each data point
# row i denotes class i's weights for each of the D dimensions
# for this example, we have 3 classes, and each data point is 5-D
W = np.array([[ 0.2 , -0.5 ,  0.1 ,  2.  ,  1.1 ],
           [ 1.5 ,  1.3 ,  2.1 ,  0.  ,  3.2 ],
           [ 0.  ,  0.25,  0.2 , -0.3 , -1.2 ]])
W

array([[ 0.2 , -0.5 ,  0.1 ,  2.  ,  1.1 ],
       [ 1.5 ,  1.3 ,  2.1 ,  0.  ,  3.2 ],
       [ 0.  ,  0.25,  0.2 , -0.3 , -1.2 ]])

In [247]:
W.shape

(3, 5)

In [257]:
# X is D x N
# D - dimensions of each data point,
# N - size of data set
# column i denotes data point x_i
# for this example, we have 4 data points in our dataset

X = np.random.rand(4,4)
X = np.array([[round(i, 2) for i in row] for row in X])
X1 = np.ones((X.shape[1]))
X = np.vstack((X,X1))
X

array([[0.44, 0.03, 0.88, 0.02],
       [0.61, 0.09, 0.15, 0.3 ],
       [0.92, 0.07, 0.97, 0.16],
       [0.62, 0.08, 1.  , 0.33],
       [1.  , 1.  , 1.  , 1.  ]])

In [258]:
X.shape

(5, 4)

In [250]:
# Y is N x 1
# Y is a column vector where each row stores the true class of x_i
Y = np.array([2,0,1,0])
Y

array([2, 0, 1, 0])

In [220]:
Y.shape

(4,)

In [221]:
# column i of WX denotes the ith data point, x_i.
# row j in column i denotes the score of the jth class for x_i.
# in each column, we want to subtract from each row the true class score,
# except for the row corresponding to the correct class.
WX = W@X
WX

array([[ 1.546 ,  1.375 ,  2.5   ,  2.295 ],
       [ 6.315 ,  2.21  ,  4.037 ,  5.459 ],
       [-0.5435, -0.2785, -0.6585, -1.16  ]])

In [222]:
WX.shape

(3, 4)

In [253]:
# returns average loss of entire data set
def svm_loss_naive(W, X, Y):
    """
    - W is K x (D+1) weight vector (K = # classes, D = # dimensions)
        - the +1 is from the bias column vector
    - X is (D+1) x N matrix of data points (N = size of data set)
        - last row of X is always 1 via bias column trick
    - Y is N x 1 column vector of true class for each x_i
    """
    delta = 1.0
    loss = 0
    scores = W@X # K x N, scores[j][i] = x_i's score for class j
    K, N = scores.shape
    for image in range(N):
        for class_ in range(K):
            correct_class = Y[image]
            if class_ == correct_class:
                continue
            loss += max(0, scores[class_][image] - \
                        scores[correct_class][image] + delta)
    
    return (loss / N) + np.sum(W**2)

In [254]:
svm_loss_naive(W,X,Y)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 6 is different from 5)

In [235]:
def svm_loss_vectorized(W, X, Y):
    """
    NOTE: Y is conceputally N x 1, but we store it as a 1-D
    array, i.e. 1 x N row vector, so we can pass it as an int
    array to choose(). (We could also pass transpose of column
    vector.)
    """
    delta = 1.0
    scores = W@X
    # correct_scores[i] = score of the true class of x_i
    correct_scores = np.choose(Y, scores)
    scores -= correct_scores
    scores[scores != 0] += delta
    
    avg_loss = np.sum(scores[scores > 0]) / len(Y)
    reg = np.sum(W**2)
    return avg_loss + reg

In [234]:
svm_loss_vectorized(W,X,Y)

29.969250000000002

In [227]:
svm_loss_vectorized(W,X,Y) == svm_loss_naive(W,X,Y)

True